//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hesa.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeedData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hesa.Logic.SeedData", typeof(SeedData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;FirstName&quot;:&quot;Vergil&quot;,&quot;LastName&quot;:&quot;Whitfeld&quot;,&quot;UserName&quot;:&quot;vwhitfeld0&quot;,&quot;Email&quot;:&quot;vwhitfeld0@google.nl&quot;},
        ///{&quot;FirstName&quot;:&quot;Mercedes&quot;,&quot;LastName&quot;:&quot;Brigdale&quot;,&quot;UserName&quot;:&quot;mbrigdale1&quot;,&quot;Email&quot;:&quot;mbrigdale1@odnoklassniki.ru&quot;},
        ///{&quot;FirstName&quot;:&quot;Ernesta&quot;,&quot;LastName&quot;:&quot;Gerbel&quot;,&quot;UserName&quot;:&quot;egerbel2&quot;,&quot;Email&quot;:&quot;egerbel2@bloglovin.com&quot;},
        ///{&quot;FirstName&quot;:&quot;Brooke&quot;,&quot;LastName&quot;:&quot;Abson&quot;,&quot;UserName&quot;:&quot;babson3&quot;,&quot;Email&quot;:&quot;babson3@merriam-webster.com&quot;},
        ///{&quot;FirstName&quot;:&quot;Mireille&quot;,&quot;LastName&quot;:&quot;Swithenby&quot;,&quot;UserName&quot;:&quot;mswithenby4&quot;,&quot;Email&quot;:&quot;mswithenby4@wix.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string seed_users {
            get {
                return ResourceManager.GetString("seed_users", resourceCulture);
            }
        }
    }
}
